"""create_statements_and_transactions

Revision ID: f5c28ee5f774
Revises: 46cf041ab0c4
Create Date: 2026-02-19 12:30:52.844776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c28ee5f774'
down_revision: Union[str, Sequence[str], None] = '46cf041ab0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('to_account_id', sa.UUID(), nullable=True, comment='For transfer type: destination account (own_account sub_type only)'),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='transactiontype'), nullable=False),
    sa.Column('sub_type', sa.Enum('salary', 'thirteenth_month', 'bonus', 'overtime', 'freelance', 'business', 'consulting', 'rental', 'interest', 'dividends', 'capital_gains', 'sss_benefit', 'philhealth_reimbursement', 'pagibig_dividend', 'government_aid', 'remittance_received', 'gift_received', 'tax_refund', 'sale_of_items', 'refund_cashback', 'other_income', 'regular', 'gift_given', 'bill_payment', 'subscription', 'other_expense', 'own_account', 'sent_to_person', 'atm_withdrawal', name='transactionsubtype'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'paste_ai', 'pdf', 'csv_import', name='transactionsource'), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Optional fee charged on this transaction (e.g. ATM fee, bank charge)'),
    sa.Column('fee_category_id', sa.UUID(), nullable=True, comment='Category for the fee (defaults to ATM Fees / Bank Transaction Fees)'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('minimum_due', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
